// import vazirFont from "@/constants/localFonts";
// import "../globals.css";
import Header from "../../components/Header";
// import { Toaster } from "react-hot-toast";
// import { AuthContextProvider } from "@/context/AuthContext";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function UserLayout({ children }) {
  return (
    // <html
    //   lang="fa"
    //   dir="rtl"
    //   // className={`h-full antialiased`}
    // >
    //   <body
    //     className={`${vazirFont.variable} font-vazir bg-background relative`}
    //   >
    //     <AuthContextProvider>
    //       <Toaster />
    <div>
          <Header />
          {children}
          </div>
    //     </AuthContextProvider>
    //   </body>
    // </html>
  );
}
